name: Build and Deploy

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t management-api .

      - name: Log in to DigitalOcean
        run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DIGITALOCEAN_USER }}" --password-stdin registry.digitalocean.com

      - name: Push Docker image
        run: |
          docker tag management-api registry.digitalocean.com/your-registry/management-api
          docker push registry.digitalocean.com/your-registry/management-api

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            docker pull registry.digitalocean.com/your-registry/management-api
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d --name your-container-name -p 8080:8080 registry.digitalocean.com/your-registry/management-api
